layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


about: "I'm Hamed, a Bachelor graduate in Computer Engineering from <a href=\"https://ut.ac.ir/\">the University of Tehran</a>. I'm passionate about distributed and data-intensive systems. I have designed and developed fintech and data analytics software and worked as a cross-functional developer. I'm a skillful engineer in Java, JS and C++ who enjoys sharing his knowledge with others through publicly available code repositories and mentorship.
I'm actively looking for a <strong>software engineer</strong> job and can start working in the EU immediately. <strong>If you are hiring, please let me know</strong>."

bio: "Besides that, I enjoy climbing, solving puzzles, travelling"

name: "Hamed Heidarian"

email: hamedheidariann@gmail.com

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  linkedin: hamed-heidarian
  github: hamedheidarian
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  stackoverflow: 7723926
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "Mahsan"
    company_url: "https://mahsan.co"
    role: "Software Engineer"
    start: "2022"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Participated in the design and development of a data analytics system </li>
    </ul>"
  - company: "IAIS"
    company_url: "https://iais.ir/"
    role: "Software Engineer"
    start: "2021"
    end: "2019"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>

        <li>Worked as a full-stack developer in Moneasy wallet using Java,
    Playframework, Hibernate, Postgresql, Angular, Redis and did some
    infrastructure works using Docker, Kubernetes, Nginx as well as some
    development in android client. We strived for developing this product
    using reactive programming paradigm as much as possible and also
    conforming to clean code and clean architecture principles. Some
    important features designed and developed by me are as follow:</li>

    <li>Campaigning and discount codes</li>
    <li>Shared accounts and force-invoice accounts</li>
    <li>Brute Force attack prevention system</li>
    <li>BI dashboard</li>
    Implementation of a new invoice system, etc
          <li> Designed a multi-level job caching mechanism, improved the response time +30 times faster than the baseline model</li>
          <li> Implemented a scalable caching service using ASP.NET, CosmosDB, and Azure Storage </li>
        </ul>"

  - company: "Kavoshcom"
    company_url: "https://www.kavoshcom.com/en/productdetail/10091/%d8%b3%d8%b1%d9%88%db%8c%d8%b3-%d8%a7%d8%a8%d8%b1%db%8c-%d9%82%d9%84%d8%a8-%d8%b3%d8%a8%d8%b2"
    role: "UI Developer"
    start: "2021"
    end: "2021"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Developed UI for a heart monitoring system using angular framework</li>
    </ul>"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name