layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


about: "I'm Hamed, a Bachelor graduate in Computer Engineering from <a href=\"https://ut.ac.ir/en\">the University of Tehran</a>. I'm passionate about distributed and data-intensive systems. I have designed and developed fintech and data analytics software and worked as a cross-functional developer. I'm a skillful engineer in Java, JS and C++ who enjoys sharing his knowledge with others through publicly available code repositories and mentorship.
I'm actively looking for a <strong>software engineer</strong> job and can start working in the EU immediately. <strong>If you are hiring, please let me know</strong>."

bio: "Besides that, I enjoy climbing, solving puzzles, travelling"

name: "Hamed Heidarian"

email: hamedheidariann@gmail.com

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: hamed-heidarian
  github: hamedheidarian
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 7723926
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "Mahsan"
    company_url: "https://mahsan.co"
    role: "Software Engineer"
    start: "2022"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li>Participated in the design and implementation of a data analytics software with service-based
architecture </li>
    <li>Took charge of implementing many key features such as fine-grained Access control, geospatial search,
and incremental histograms using technologies such as Spring Framework, Yugabyte DB,
Elasticsearch</li>
    <li>Applied BDD testing using Cucumber, Testcontainers, AssertJ</li>
    <li>Containerized the project and provided service infrastructures such as configured monitoring, ci
pipeline and orchestration</li>
    <li>Collaborated in the implementation of the data modeling module</li>
    <li>Researched and presented solutions to major issues like the selection of database, design of fine-grained
access control in Elasticsearch, consistency in distributed systems and concurrency issues, best practices
of tools, etc</li>
    <li>Improved my knowledge of Agile methodologies and Spring framework ecosystem and skill of
documentation</li>
    <li> Contributed with other teams in the company to integrate with their product</li>
    </ul>"
  - company: "IAIS"
    company_url: "https://iais.ir/"
    role: "Software Engineer"
    start: "2021"
    end: "2019"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>

        <li>Added features to <a href=https://moneasy.ir>an e-wallet</a> using Play Framework, Hibernate, Postgresql and Redis and did
            some infrastructure works using Docker, K8s, as well as some development in the android client and
            developed frontend using Angular</li>

    <li>Some of the features fully designed and developed by me are:
        </br>– Campaigning and discount codes(with support for network marketing)
        </br>– Shared accounts (accounts that divide all received money to them is between some other accounts
        by percentage or fixed amount) and force-invoice accounts
        </br>– Brute force attack prevention system(using AOP with support for roles, unauthorized limit, etc)
        </br>– Data warehousing and BI dashboard(using ClickHouse and Metabase), etc
        </br>– Containerized the project and created K8s cluster and configurations
    </li>

    <li>Was appointed as deputy of the project’s tech lead in his three months leave</li>
    <li>Added some features to ticket(multi-stage payment) system</li>
    <li>Reduced a significant amount of code and development effort by refactoring existing codes (e.g. by using
    generics)</li>
    <li> Collaborated in the implementation of the settlement system with Bank and Shapara</li>
    <li> Added many features to frontend and android client e.g. auto OTP detection as well as bug fixes </li>
    <li> Fixed bugs reported by customers, Revamped the invoice system, Did load testing with Locust etc </li>
   </ul>"

  - company: "Kavoshcom"
    company_url: "https://www.kavoshcom.com/en/productdetail/10091/%d8%b3%d8%b1%d9%88%db%8c%d8%b3-%d8%a7%d8%a8%d8%b1%db%8c-%d9%82%d9%84%d8%a8-%d8%b3%d8%a8%d8%b2"
    role: "UI Developer"
    start: "2021"
    end: "2021"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Developed UI for a heart monitoring system using angular framework</li>
    </ul>"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 20
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
